version: "3.8"

services:
  app:
    build: .
    container_name: product-management
    ports:
      - "5555:5555"
    environment:
      PORT: 5555
      MONGODB_URI: mongodb://mongo:27017/product-management

      MAIL_USER: ${MAIL_USER}
      PASSWORD_USER: ${PASSWORD_USER}

      CLOUD_NAME: ${CLOUD_NAME}
      API_KEY: ${API_KEY}
      API_SECRET: ${API_SECRET}

    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:latest
    container_name: product-management-mongo
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
